import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const read=f=>fs.readFileSync(path.join(ROOT,f),"utf8");
const exists=f=>fs.existsSync(path.join(ROOT,f));
test("Node runtime is pinned consistently to 24",()=>{const pkg=JSON.parse(read("package.json"));assert.equal(pkg.engines.node,"24.x");assert.equal(read(".nvmrc").trim(),"24")});
test("Vercel is configured for TanStack Start",()=>{const v=JSON.parse(read("vercel.json"));assert.equal(v.framework,"vite")});
test("SSR client entry uses StartClient hydration",()=>assert.match(read("src/client.tsx"),/StartClient/));
test("Supabase configuration has one public source of truth",()=>{const client=read("src/integrations/supabase/client.ts");assert.match(client,/config\/public/);assert.doesNotMatch(client,/VITE_SUPABASE_URL\s*\|\|\s*["']/)});
test("Admin auth cannot grant access from local mock state",()=>{const hook=read("src/hooks/useAdmin.ts");assert.doesNotMatch(hook,/localStorage|getItem\(|mock.*admin/i);assert.match(hook,/admin_users/) });
test("Admin route boundary is isolated from the control-room implementation",()=>assert.match(read("src/routes/admin.lazy.tsx"),/components\/admin\/AdminControlRoom/));
test("Legacy login patch script is absent",()=>assert.equal(exists("patch_login.cjs"),false));
test("Chat API does not use wildcard CORS",()=>{const api=read("src/routes/api.chat.ts");assert.doesNotMatch(api,/Access-Control-Allow-Origin["']?\s*:\s*["']\*["']/);assert.match(api,/isCorsOriginAllowed/);assert.match(api,/RATE_LIMIT_WINDOW_MS/);assert.match(api,/MAX_BODY_BYTES/) });
test("Package manifest and lockfile root dependencies are compatible",()=>{const pkg=JSON.parse(read("package.json"));const lock=JSON.parse(read("package-lock.json"));const root=lock.packages?.[""];assert.ok(root,"package-lock root package entry is missing");for(const [name,range] of Object.entries(pkg.dependencies))assert.equal(root.dependencies?.[name],range,`dependency ${name} differs`);for(const [name,range] of Object.entries(pkg.devDependencies)){assert.equal(root.devDependencies?.[name],range,`devDependency ${name} differs`) }assert.deepEqual(root.engines,pkg.engines)});
test("Phase one verification commands exist",()=>{const pkg=JSON.parse(read("package.json"));assert.equal(pkg.scripts?.test,"node --test tests/*.test.mjs");assert.equal(typeof pkg.scripts?.diagnose,"string");assert.equal(typeof pkg.scripts?.check,"string")});
