import { useEffect, useState } from "react";
import { RefreshCw, Save } from "lucide-react";
import { toast } from "sonner";
import { useServerFn } from "@tanstack/react-start";
import { listAdminReelItems, updateAdminReelItem } from "@/lib/admin.reel.functions";

export function ReelManager() {
  const load=useServerFn(listAdminReelItems); const update=useServerFn(updateAdminReelItem);
  const [rows,setRows]=useState<any[]>([]); const [busy,setBusy]=useState(false);
  const refresh=async()=>{setBusy(true);try{const result=await load({data:{}});setRows(result.rows??[]);}catch(error){toast.error(error instanceof Error?error.message:"Reel registry is not available yet.");}finally{setBusy(false);}};
  useEffect(()=>{void refresh();},[]);
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><div className="mono text-[10px] tracking-[0.25em] text-sky-300/70">CONTENT / REEL</div><h2 className="display mt-1 text-3xl text-metal">Selected Reel.</h2><p className="mt-2 text-sm text-slate-500">Order, publish state and manual work colour. The public fallback remains the current project source until the Reel migration is applied.</p></div><button type="button" onClick={()=>void refresh()} disabled={busy} className="inline-flex min-h-10 items-center gap-2 border border-white/[0.08] px-3 text-xs text-slate-400"><RefreshCw size={13} className={busy?"animate-spin":""}/>Refresh</button></header>
  {rows.length===0?<div className="border-2 border-dashed border-white/[0.08] p-10 text-center text-sm text-slate-600">No reel registry rows are available. This is expected until the Phase 14 migration is applied.</div>:<div className="space-y-2">{rows.map((row,index)=><article key={row.id} className="grid gap-3 border-2 border-white/[0.08] p-4 md:grid-cols-[minmax(0,1fr)_120px_150px_130px] md:items-center"><div><div className="text-sm text-white">{row.title}</div><div className="mt-1 text-xs text-slate-600">{row.client||"No client"} · {row.discipline||"Project"} · {row.year||"No year"}</div></div><label className="text-xs text-slate-500">Order<input type="number" value={row.display_order??index} onChange={(e)=>setRows(r=>r.map(x=>x.id===row.id?{...x,display_order:Number(e.target.value)}:x))} className="adm-input mt-1"/></label><label className="inline-flex items-center gap-2 text-xs text-slate-500"><input type="checkbox" checked={Boolean(row.is_published)} onChange={(e)=>setRows(r=>r.map(x=>x.id===row.id?{...x,is_published:e.target.checked}:x))}/>Published</label><button type="button" onClick={async()=>{try{await update({data:{id:row.id,display_order:Number(row.display_order),is_published:Boolean(row.is_published),accent_color:row.accent_color||null}});toast.success("Reel item saved");}catch(error){toast.error(error instanceof Error?error.message:"Reel update failed");}}} className="inline-flex min-h-10 items-center justify-center gap-2 border-2 border-emerald-300/20 px-3 text-sm text-emerald-200"><Save size={13}/>Save</button></article>)}</div>}</div>;
}
