/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminStudioRouteImport } from './routes/admin.studio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ITokenRouteImport } from './routes/i.$token'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioBusinessCardRouteImport } from './routes/studio.business-card'
import { Route as ApiStudioAdminRouteImport } from './routes/api.studio-admin'
import { Route as ApiStudioBackgroundRouteImport } from './routes/api.studio-background'
import { Route as StudioBackgroundRouteImport } from './routes/studio.background'
import { Route as ApiStudioCreativeRouteImport } from './routes/api.studio-creative'
import { Route as ApiStudioPublishRouteImport } from './routes/api.studio-publish'
import { Route as ApiStudioVcardRouteImport } from './routes/api.studio-vcard'
import { Route as ApiStudioEmailRouteImport } from './routes/api.studio-email'
import { Route as CardTokenRouteImport } from './routes/card.$token'
import { Route as StudioIdentityRouteImport } from './routes/studio.identity'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const AdminStudioRoute = AdminStudioRouteImport.update({ id: '/admin/studio', path: '/admin/studio', getParentRoute: () => rootRouteImport } as any)
const ContactRoute = ContactRouteImport.update({ id: '/contact', path: '/contact', getParentRoute: () => rootRouteImport } as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const CredentialsRoute = CredentialsRouteImport.update({ id: '/credentials', path: '/credentials', getParentRoute: () => rootRouteImport } as any)
const McpRoute = McpRouteImport.update({ id: '/mcp', path: '/mcp', getParentRoute: () => rootRouteImport } as any)
const ServicesRoute = ServicesRouteImport.update({ id: '/services', path: '/services', getParentRoute: () => rootRouteImport } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({ id: '/sitemap.xml', path: '/sitemap.xml', getParentRoute: () => rootRouteImport } as any)
const Char91DotmcpChar93ListToolsRoute = Char91DotmcpChar93ListToolsRouteImport.update({ id: '/.mcp/list-tools', path: '/.mcp/list-tools', getParentRoute: () => rootRouteImport } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute = Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({ id: '/.well-known/oauth-protected-resource', path: '/.well-known/oauth-protected-resource', getParentRoute: () => rootRouteImport } as any)
const ApiChatRoute = ApiChatRouteImport.update({ id: '/api/chat', path: '/api/chat', getParentRoute: () => rootRouteImport } as any)
const ITokenRoute = ITokenRouteImport.update({ id: '/i/$token', path: '/i/$token', getParentRoute: () => rootRouteImport } as any)
const PortfolioRoute = PortfolioRouteImport.update({ id: '/portfolio', path: '/portfolio', getParentRoute: () => rootRouteImport } as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({ id: '/portfolio/', path: '/portfolio', getParentRoute: () => rootRouteImport } as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({ id: '/portfolio/$slug', path: '/portfolio/$slug', getParentRoute: () => rootRouteImport } as any)
const Char91DotmcpChar93InvokeToolToolRoute = Char91DotmcpChar93InvokeToolToolRouteImport.update({ id: '/.mcp/invoke-tool/$tool', path: '/.mcp/invoke-tool/$tool', getParentRoute: () => rootRouteImport } as any)
const StudioRoute = StudioRouteImport.update({ id: '/studio', path: '/studio', getParentRoute: () => rootRouteImport } as any)
const StudioBusinessCardRoute = StudioBusinessCardRouteImport.update({ id: '/studio/business-card', path: '/studio/business-card', getParentRoute: () => rootRouteImport } as any)
const ApiStudioAdminRoute = ApiStudioAdminRouteImport.update({ id: '/api/studio/admin', path: '/api/studio/admin', getParentRoute: () => rootRouteImport } as any)
const ApiStudioBackgroundRoute = ApiStudioBackgroundRouteImport.update({ id: '/api/studio/background', path: '/api/studio/background', getParentRoute: () => rootRouteImport } as any)
const StudioBackgroundRoute = StudioBackgroundRouteImport.update({ id: '/studio/background', path: '/studio/background', getParentRoute: () => rootRouteImport } as any)
const ApiStudioCreativeRoute = ApiStudioCreativeRouteImport.update({ id: '/api/studio/creative', path: '/api/studio/creative', getParentRoute: () => rootRouteImport } as any)
const ApiStudioPublishRoute = ApiStudioPublishRouteImport.update({ id: '/api/studio/publish', path: '/api/studio/publish', getParentRoute: () => rootRouteImport } as any)
const ApiStudioVcardRoute = ApiStudioVcardRouteImport.update({ id: '/api/studio/vcard', path: '/api/studio/vcard', getParentRoute: () => rootRouteImport } as any)
const ApiStudioEmailRoute = ApiStudioEmailRouteImport.update({ id: '/api/studio/email', path: '/api/studio/email', getParentRoute: () => rootRouteImport } as any)
const CardTokenRoute = CardTokenRouteImport.update({ id: '/card/$token', path: '/card/$token', getParentRoute: () => rootRouteImport } as any)
const StudioIdentityRoute = StudioIdentityRouteImport.update({ id: '/studio/identity', path: '/studio/identity', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin/studio': typeof AdminStudioRoute
  '/contact': typeof ContactRoute
  '/credentials': typeof CredentialsRoute
  '/mcp': typeof McpRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/i/$token': typeof ITokenRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/studio': typeof StudioRoute
  '/studio/business-card': typeof StudioBusinessCardRoute
  '/api/studio/admin': typeof ApiStudioAdminRoute
  '/api/studio/background': typeof ApiStudioBackgroundRoute
  '/studio/background': typeof StudioBackgroundRoute
  '/api/studio/creative': typeof ApiStudioCreativeRoute
  '/api/studio/publish': typeof ApiStudioPublishRoute
  '/api/studio/vcard': typeof ApiStudioVcardRoute
  '/api/studio/email': typeof ApiStudioEmailRoute
  '/card/$token': typeof CardTokenRoute
  '/studio/identity': typeof StudioIdentityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin/studio': typeof AdminStudioRoute
  '/contact': typeof ContactRoute
  '/credentials': typeof CredentialsRoute
  '/mcp': typeof McpRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/i/$token': typeof ITokenRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/studio': typeof StudioRoute
  '/studio/business-card': typeof StudioBusinessCardRoute
  '/studio/background': typeof StudioBackgroundRoute
  '/api/studio/admin': typeof ApiStudioAdminRoute
  '/api/studio/background': typeof ApiStudioBackgroundRoute
  '/api/studio/creative': typeof ApiStudioCreativeRoute
  '/api/studio/publish': typeof ApiStudioPublishRoute
  '/api/studio/vcard': typeof ApiStudioVcardRoute
  '/api/studio/email': typeof ApiStudioEmailRoute
  '/card/$token': typeof CardTokenRoute
  '/studio/identity': typeof StudioIdentityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/studio'
    | '/contact'
    | '/credentials'
    | '/mcp'
    | '/services'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/i/$token'
    | '/portfolio'
    | '/portfolio/$slug'
    | '/portfolio/'
    | '/.mcp/invoke-tool/$tool'
    | '/studio'
    | '/studio/business-card'
    | '/api/studio/admin'
    | '/api/studio/background'
    | '/studio/background'
    | '/api/studio/creative'
    | '/api/studio/publish'
    | '/api/studio/vcard'
    | '/api/studio/email'
    | '/card/$token'
    | '/studio/identity'
  fileRoutesByTo: FileRoutesByTo
  to: FileRoutesByTo extends never ? never : keyof FileRoutesByTo
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/studio'
    | '/contact'
    | '/credentials'
    | '/mcp'
    | '/services'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/i/$token'
    | '/portfolio'
    | '/portfolio/$slug'
    | '/portfolio/'
    | '/.mcp/invoke-tool/$tool'
    | '/studio'
    | '/studio/business-card'
    | '/api/studio/admin'
    | '/api/studio/background'
    | '/studio/background'
    | '/api/studio/creative'
    | '/api/studio/publish'
    | '/api/studio/vcard'
    | '/api/studio/email'
    | '/card/$token'
    | '/studio/identity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminStudioRoute: typeof AdminStudioRoute
  ContactRoute: typeof ContactRoute
  CredentialsRoute: typeof CredentialsRoute
  McpRoute: typeof McpRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ITokenRoute: typeof ITokenRoute
  PortfolioRoute: typeof PortfolioRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  StudioRoute: typeof StudioRoute
  StudioBusinessCardRoute: typeof StudioBusinessCardRoute
  ApiStudioAdminRoute: typeof ApiStudioAdminRoute
  ApiStudioBackgroundRoute: typeof ApiStudioBackgroundRoute
  StudioBackgroundRoute: typeof StudioBackgroundRoute
  ApiStudioCreativeRoute: typeof ApiStudioCreativeRoute
  ApiStudioPublishRoute: typeof ApiStudioPublishRoute
  ApiStudioVcardRoute: typeof ApiStudioVcardRoute
  ApiStudioEmailRoute: typeof ApiStudioEmailRoute
  CardTokenRoute: typeof CardTokenRoute
  StudioIdentityRoute: typeof StudioIdentityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
    '/admin/studio': { id: '/admin/studio'; path: '/admin/studio'; fullPath: '/admin/studio'; preLoaderRoute: typeof AdminStudioRouteImport; parentRoute: typeof rootRouteImport }
    '/contact': { id: '/contact'; path: '/contact'; fullPath: '/contact'; preLoaderRoute: typeof ContactRouteImport; parentRoute: typeof rootRouteImport }
    '/credentials': { id: '/credentials'; path: '/credentials'; fullPath: '/credentials'; preLoaderRoute: typeof CredentialsRouteImport; parentRoute: typeof rootRouteImport }
    '/mcp': { id: '/mcp'; path: '/mcp'; fullPath: '/mcp'; preLoaderRoute: typeof McpRouteImport; parentRoute: typeof rootRouteImport }
    '/services': { id: '/services'; path: '/services'; fullPath: '/services'; preLoaderRoute: typeof ServicesRouteImport; parentRoute: typeof rootRouteImport }
    '/sitemap.xml': { id: '/sitemap.xml'; path: '/sitemap.xml'; fullPath: '/sitemap.xml'; preLoaderRoute: typeof SitemapDotxmlRouteImport; parentRoute: typeof rootRouteImport }
    '/.mcp/list-tools': { id: '/.mcp/list-tools'; path: '/.mcp/list-tools'; fullPath: '/.mcp/list-tools'; preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport; parentRoute: typeof rootRouteImport }
    '/.well-known/oauth-protected-resource': { id: '/.well-known/oauth-protected-resource'; path: '/.well-known/oauth-protected-resource'; fullPath: '/.well-known/oauth-protected-resource'; preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport; parentRoute: typeof rootRouteImport }
    '/api/chat': { id: '/api/chat'; path: '/api/chat'; fullPath: '/api/chat'; preLoaderRoute: typeof ApiChatRouteImport; parentRoute: typeof rootRouteImport }
    '/i/$token': { id: '/i/$token'; path: '/i/$token'; fullPath: '/i/$token'; preLoaderRoute: typeof ITokenRouteImport; parentRoute: typeof rootRouteImport }
    '/portfolio': { id: '/portfolio'; path: '/portfolio'; fullPath: '/portfolio'; preLoaderRoute: typeof PortfolioRouteImport; parentRoute: typeof rootRouteImport }
    '/portfolio/': { id: '/portfolio/'; path: '/portfolio'; fullPath: '/portfolio/'; preLoaderRoute: typeof PortfolioIndexRouteImport; parentRoute: typeof rootRouteImport }
    '/portfolio/$slug': { id: '/portfolio/$slug'; path: '/portfolio/$slug'; fullPath: '/portfolio/$slug'; preLoaderRoute: typeof PortfolioSlugRouteImport; parentRoute: typeof rootRouteImport }
    '/.mcp/invoke-tool/$tool': { id: '/.mcp/invoke-tool/$tool'; path: '/.mcp/invoke-tool/$tool'; fullPath: '/.mcp/invoke-tool/$tool'; preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport; parentRoute: typeof rootRouteImport }
    '/studio': { id: '/studio'; path: '/studio'; fullPath: '/studio'; preLoaderRoute: typeof StudioRouteImport; parentRoute: typeof rootRouteImport }
    '/studio/business-card': { id: '/studio/business-card'; path: '/studio/business-card'; fullPath: '/studio/business-card'; preLoaderRoute: typeof StudioBusinessCardRouteImport; parentRoute: typeof rootRouteImport }
    '/api/studio/admin': { id: '/api/studio/admin'; path: '/api/studio/admin'; fullPath: '/api/studio/admin'; preLoaderRoute: typeof ApiStudioAdminRouteImport; parentRoute: typeof rootRouteImport }
    '/api/studio/background': { id: '/api/studio/background'; path: '/api/studio/background'; fullPath: '/api/studio/background'; preLoaderRoute: typeof ApiStudioBackgroundRouteImport; parentRoute: typeof rootRouteImport }
    '/studio/background': { id: '/studio/background'; path: '/studio/background'; fullPath: '/studio/background'; preLoaderRoute: typeof StudioBackgroundRouteImport; parentRoute: typeof rootRouteImport }
    '/api/studio/creative': { id: '/api/studio/creative'; path: '/api/studio/creative'; fullPath: '/api/studio/creative'; preLoaderRoute: typeof ApiStudioCreativeRouteImport; parentRoute: typeof rootRouteImport }
    '/api/studio/publish': { id: '/api/studio/publish'; path: '/api/studio/publish'; fullPath: '/api/studio/publish'; preLoaderRoute: typeof ApiStudioPublishRouteImport; parentRoute: typeof rootRouteImport }
    '/api/studio/vcard': { id: '/api/studio/vcard'; path: '/api/studio/vcard'; fullPath: '/api/studio/vcard'; preLoaderRoute: typeof ApiStudioVcardRouteImport; parentRoute: typeof rootRouteImport }
    '/api/studio/email': { id: '/api/studio/email'; path: '/api/studio/email'; fullPath: '/api/studio/email'; preLoaderRoute: typeof ApiStudioEmailRouteImport; parentRoute: typeof rootRouteImport }
    '/card/$token': { id: '/card/$token'; path: '/card/$token'; fullPath: '/card/$token'; preLoaderRoute: typeof CardTokenRouteImport; parentRoute: typeof rootRouteImport }
    '/studio/identity': { id: '/studio/identity'; path: '/studio/identity'; fullPath: '/studio/identity'; preLoaderRoute: typeof StudioIdentityRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AdminRoute,
  AdminStudioRoute,
  ContactRoute,
  CredentialsRoute,
  McpRoute,
  ServicesRoute,
  SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute,
  ITokenRoute,
  PortfolioRoute,
  PortfolioSlugRoute,
  PortfolioIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute,
  StudioRoute,
  StudioBusinessCardRoute,
  ApiStudioAdminRoute,
  ApiStudioBackgroundRoute,
  StudioBackgroundRoute,
  ApiStudioCreativeRoute,
  ApiStudioPublishRoute,
  ApiStudioVcardRoute,
  ApiStudioEmailRoute,
  CardTokenRoute,
  StudioIdentityRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}